### PR TITLE
Fix secrets directory structure

### PR DESCRIPTION
**Pull request by lxe**
cc @sh1mmer @Raynos

### CODE REVIEW

**Comment by sh1mmer** [comment]
This lgtm. Can I get a second?

**Comment by kriskowal** [comment]
Looks correct. New policy is secrets/secrets-$NODE_ENV.json, where $NODE_ENV is "production" or "test" or whatnot.

**Comment by Raynos** [comment]
lgtm.

**Comment by lxe** [comment]
> Looks correct. New policy is secrets/secrets-$NODE_ENV.json, where $NODE_ENV is "production" or "test" or whatnot.

@kriskowal so uh it's no longer `config/secrets-$NODE_ENV`?

**Comment by kriskowal** [comment]
@lxe, no ignore me. I mis-read what I was seeing.

**Comment by lxe** [comment]
@kriskowal lol because `secrets/secrets-NODE_ENV` would be a lot better...

**Pull request merged**
